apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;
    events {
      worker_connections  1024;
    }
    http {
    log_format  main
        'remote_addr:$remote_addr\t'
        'time_local:$time_local\t'
        'method:$request_method\t'
        'uri:$request_uri\t'
        'host:$host\t'
        'status:$status\t'
        'bytes_sent:$body_bytes_sent\t'
        'referer:$http_referer\t'
        'useragent:$http_user_agent\t'
        'forwardedfor:$http_x_forwarded_for\t'
        'request_time:$request_time';

      upstream user-service {
        server user-service:80;
      }

      upstream order-service {
        server order-service:80;
      }

      upstream payment-service {
        server payment-service:80;
      }

      server {
        listen 80;

        location /users {
          proxy_pass http://user-service;
        }

        location /orders {
          proxy_pass http://order-service;
        }

        location /payments {
          proxy_pass http://payment-service;
        }
      }
    }

  virtualhost.conf: |
    upstream app {
      server localhost:8080;
      keepalive 1024;
    }
    server {
      listen 80 default_server;
      root /usr/local/app;
      access_log /var/log/nginx/app.access_log main;
      error_log /var/log/nginx/app.error_log;
      location / {
        proxy_pass http://app/;
        proxy_http_version 1.1;
      }
    }
